### ISSUE TITLE
We don't have degeneratedlabs repo anymore

### ISSUE THREAD

**Issue by XayOn** [ivanlei/airodump-iv#1]
Ey there. I'm degeneratedlabs (now dlabs, dlabs.co)'s repository mantainer.
I found your repo by chance looking for some stuff (I'm also airoscript-ng's dev) and I was surprised to see that you use our old (really old) repository. We've let that repository (even the domain) down.

I plan to put it back soon, but if it's only for aircrack-ng, you could use official repos.
It should even be in debian since the GPL fix by moving aircrack-ng to use gnutls instead of openssl.

Thanks

**Comment by ivanlei** [comment]
I haven't looked at this project in a while. I'll replace the repo stuff in a couple of days. Thanks for the heads up.

**Comment by XayOn** [comment]
You are welcome.
Also that probably explains the amazing traffic we were getting in the
hackerspace's server :-P

**Comment by ivanlei** [comment]
fixed in 1d099d0ccaa3c71debfa7dc2032e41b44a64ea6b
